#!/bin/bash
echo "📡 ESTABLECIENDO CONEXIÓN CON EL NODO GOKHAN-2026..."
sleep 2
echo "🔐 CARGANDO PROTOCOLOS DE ENCRIPTACIÓN FISICA..."
sleep 2
echo "🥾 BUSCANDO HARDWARE DETECTADO (NFC GATEKEEPER)..."
sleep 2
echo "⚠️ ERROR: GEAR NO DETECTADO. POR FAVOR, ACERQUE SU BOTA AL LECTOR."
